package webAddressbook;// Generated by Selenium IDE
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.ITestResult;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.Test;

import java.io.File;
import java.io.IOException;
import java.time.Duration;

@Test
class GroupCeationTestsTest {
  public static void main(String[] args) throws InterruptedException {
    System.setProperty("webdriver.gecko.driver", "C:\\Webdriver\\chromedriver.exe");
    WebDriver driver = new ChromeDriver();
    //driver.get("https://google.com");
    driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));

    driver.get("http://localhost/addressbook/group.php");
    //driver.findElement(By.name("user")).click();
    WebElement login = driver.findElement(By.xpath("//input[@name='user']"));
    login.sendKeys("admin");
    Thread.sleep(2000);

    WebElement pass = driver.findElement(By.xpath("//input[@name='pass']"));
    pass.sendKeys("secret");
    Thread.sleep(2000);

    WebElement submit = driver.findElement(By.xpath("//input[@name='pass']"));
    WebElement element = driver.findElement(By.xpath("//input[@type='submit']"));
    element.click();


    driver.manage().window().setSize(new Dimension(2576, 1416));
    driver.findElement(By.name("new")).click();

    driver.findElement(By.name("group_name")).click();
    driver.findElement(By.cssSelector("input:nth-child(2)")).sendKeys("Kim");
    Thread.sleep(2000);

    driver.findElement(By.name("group_header1")).click();
    driver.findElement(By.name("group_header1")).sendKeys("grup1");
    Thread.sleep(2000);

    driver.findElement(By.name("group_footer")).click();
    driver.findElement(By.name("group_footer")).sendKeys("grup3");
    driver.findElement(By.name("submit")).click();
    Thread.sleep(2000);

    driver.findElement(By.linkText("group page")).click();
    Thread.sleep(2000);
    driver.quit();
  }

  @AfterMethod
  public void takeScreenShotOnFailure(ITestResult testResult) throws IOException {
    if (testResult.getStatus() == ITestResult.FAILURE) {
      File scrFile = ((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);
      FileUtils.copyFile(scrFile, new File("errorScreenshots\\" + testResult.getName() + "-"
              + Arrays.toString(testResult.getParameters()) +  ".jpg"));
    }
  }


}
